---
- name: reload systemd
  command: systemctl --system daemon-reload
  notify:
    - restart daemons
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15) or (is_coreos)

- name: restart kubelet
  service: name=kubelet state=restarted
